"""
Seed ALL 195 UN-recognized countries into the geographic catalog.
The original seed_geo.py created 20 countries with rich data.
This command adds the remaining 175 countries, each with regions,
major cities, descriptions, and Unsplash imagery.

Run: python3 manage.py seed_geo_all
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from shop.models import Country, Region, City, Product
import hashlib


class Command(BaseCommand):
    help = 'Seed all 195 UN-recognized countries with regions and cities.'

    # ── Helpers ──────────────────────────────────────────────
    @staticmethod
    def _slugify(text):
        """Simple slugify for region/city names."""
        import re
        slug = text.lower().strip()
        slug = re.sub(r'[^\w\s-]', '', slug)
        slug = re.sub(r'[\s_]+', '-', slug)
        slug = re.sub(r'-+', '-', slug)
        return slug.strip('-')

    @staticmethod
    def _img(seed_text, w=1200):
        """Generate a deterministic Unsplash source URL for a given text seed."""
        import re
        clean = re.sub(r'[^a-zA-Z0-9]', '', seed_text).lower()
        # Use a set of known-good Unsplash photo IDs cycling through for variety
        # but deterministic based on the text hash
        photo_ids = [
            '1513622470522-26c3c8a854bc',
            '1597212720156-3a2c0c4b8e36',
            '1508009603885-50cf7c579365',
            '1573152958734-1922c188fba3',
            '1597212618440-406323764935',
            '1559827260-dc66d52bef19',
            '1589909202802-8f4aadce1849',
            '1572252009286-268acec5ca0a',
            '1580983688229-996cd9a3c6e0',
            '1518738545787-4a3a3a3a3a3b',
            '1599887515723-39698b8c2a63',
            '1539067638422-76c3c8d4a3e3',
            '1516550893923-42d28e5677af',
            '1599661046289-e31897846e41',
            '1599227390096-cd0aeb893e3b',
        ]
        h = int(hashlib.md5(clean.encode()).hexdigest(), 16)
        pid = photo_ids[h % len(photo_ids)]
        return f'https://images.unsplash.com/photo-{pid}?w={w}&q=80'

    @staticmethod
    def _region_slug(country_slug, region_name):
        """Generate a unique region slug incorporating country prefix if needed."""
        import re
        base = Command._slugify(region_name)
        return f'{country_slug}-{base}' if base else country_slug

    @staticmethod
    def _city_slug(region_s, city_name):
        """Generate a unique city slug."""
        return Command._slugify(city_name)

    # ── Data: 175 remaining countries ──────────────────────
    # Each entry: (name, slug, description, [(region_name, [city_names]), ...])
    ADDITIONAL_COUNTRIES = [
        # ═══ A ═══
        ('Afghanistan', 'afghanistan',
         'A crossroads of ancient civilizations — Kabul\u2019s bazaars, Bamiyan\u2019s cliffs, and Silk Road heritage.',
         [('Kabul Province', ['Kabul', 'Charikar']),
          ('Herat Province', ['Herat']),
          ('Balkh Province', ['Mazar-i-Sharif'])]),
        ('Albania', 'albania',
         'Adriatic coastline and Ottoman-era towns — Tirana\u2019s energy meets Berat\u2019s living history.',
         [('Tirana District', ['Tirana', 'Durr\u00ebs']),
          ('Gjirokast\u00ebr', ['Gjirokast\u00ebr', 'Sarand\u00eb']),
          ('Kor\u00e7\u00eb', ['Kor\u00e7\u00eb'])]),
        ('Algeria', 'algeria',
         'The Maghreb\u2019s largest nation — Casbah of Algiers, Sahara dunes, and Roman ruins at Djemila.',
         [('Algiers Province', ['Algiers']),
          ('Oran Province', ['Oran']),
          ('Constantine Province', ['Constantine']),
          ('Annaba Province', ['Annaba'])]),
        ('Andorra', 'andorra',
         'A pygmy principality in the Pyrenees — tax-free shopping and ski resorts.',
         [('Andorra la Vella', ['Andorra la Vella', 'Escaldes-Engordany']),
          ('Canillo', ['Canillo', 'El Pas de la Casa'])]),
        ('Angola', 'angola',
         'Atlantic coastline, Portuguese heritage, and vast mineral wealth.',
         [('Luanda Province', ['Luanda']),
          ('Hu\u00edla', ['Lubango']),
          ('Benguela Province', ['Benguela'])]),
        ('Antigua and Barbuda', 'antigua-and-barbuda',
         'Twin-island Caribbean paradise — 365 beaches and Nelson\u2019s Dockyard.',
         [('Saint John', ['Saint John\u2019s']),
          ('Saint Philip', ['Codrington'])]),
        ('Argentina', 'argentina',
         'From Patagonian glaciers to tango halls of Buenos Aires — pampas, wine, and Andean peaks.',
         [('Buenos Aires', ['Buenos Aires', 'La Plata']),
          ('Mendoza', ['Mendoza']),
          ('C\u00f3rdoba', ['C\u00f3rdoba']),
          ('Patagonia', ['Bariloche', 'Ushuaia'])]),
        ('Armenia', 'armenia',
         'One of the world\u2019s oldest Christian nations — monasteries, Mt. Ararat views, and brandy.',
         [('Yerevan', ['Yerevan']),
          ('Kotayk', ['Garni', 'Tsaghkadzor']),
          ('Shirak', ['Gyumri'])]),
        ('Austria', 'austria',
         'Imperial Vienna, alpine Tyrol, and Salzburg\u2019s musical legacy.',
         [('Vienna', ['Vienna']),
          ('Salzburg', ['Salzburg']),
          ('Tyrol', ['Innsbruck', 'Kitzb\u00fchel']),
          ('Styria', ['Graz'])]),
        ('Azerbaijan', 'azerbaijan',
         'Where East meets West — Baku\u2019s Flame Towers and the Caspian shore.',
         [('Absheron', ['Baku']),
          ('Ganja-Gazakh', ['Ganja']),
          ('Aran', ['Mingachevir'])]),
        # ═══ B ═══
        ('Bahamas', 'bahamas',
         'Turquoise waters, pink-sand beaches, and Junkanoo celebrations.',
         [('New Providence', ['Nassau']),
          ('Grand Bahama', ['Freeport']),
          ('Exuma', ['George Town'])]),
        ('Bahrain', 'bahrain',
         'Island kingdom of pearl-diving heritage and Formula One nights.',
         [('Capital Governorate', ['Manama']),
          ('Muharraq', ['Muharraq'])]),
        ('Bangladesh', 'bangladesh',
         'Delta of the Ganges and Brahmaputra — lush greenery, the Sundarbans, and Dhaka\u2019s energy.',
         [('Dhaka Division', ['Dhaka', 'Narayanganj']),
          ('Chittagong Division', ['Chittagong']),
          ('Khulna Division', ['Khulna'])]),
        ('Barbados', 'barbados',
         'Rum, cricket, and Caribbean colonial charm.',
         [('Saint Michael', ['Bridgetown']),
          ('Christ Church', ['Oistins'])]),
        ('Belarus', 'belarus',
         'Forest-covered heartland — Minsk\u2019s Soviet boulevards and Mir Castle.',
         [('Minsk Region', ['Minsk']),
          ('Grodno Region', ['Grodno']),
          ('Brest Region', ['Brest'])]),
        ('Belgium', 'belgium',
         'Chocolate, beer, and EU institutions — Bruges\u2019 canals and Brussels\u2019 grand squares.',
         [('Brussels-Capital', ['Brussels']),
          ('West Flanders', ['Bruges']),
          ('Antwerp', ['Antwerp']),
          ('Li\u00e8ge', ['Li\u00e8ge'])]),
        ('Belize', 'belize',
         'Caribbean coral reef, Mayan ruins, and jungle wildlife.',
         [('Belize District', ['Belize City']),
          ('Cayo', ['San Ignacio'])]),
        ('Benin', 'benin',
         'Birthplace of Vodun and the Dahomey Kingdom — Ouidah\u2019s slave route and stilt villages.',
         [('Littoral', ['Cotonou']),
          ('Atlantique', ['Porto-Novo'])]),
        ('Bhutan', 'bhutan',
         'The last Himalayan Buddhist kingdom — Tiger\u2019s Nest and Gross National Happiness.',
         [('Thimphu District', ['Thimphu']),
          ('Paro Valley', ['Paro']),
          ('Punakha', ['Punakha'])]),
        ('Bolivia', 'bolivia',
         'Salar de Uyuni salt flats, Lake Titicaca, and the world\u2019s highest capital.',
         [('La Paz Department', ['La Paz', 'El Alto']),
          ('Santa Cruz Department', ['Santa Cruz de la Sierra']),
          ('Cochabamba', ['Cochabamba'])]),
        ('Bosnia and Herzegovina', 'bosnia-and-herzegovina',
         'Ottoman bridges, Austro-Hungarian facades, and stunning mountain landscapes.',
         [('Sarajevo Canton', ['Sarajevo']),
          ('Herzegovina-Neretva', ['Mostar']),
          ('Banja Luka', ['Banja Luka'])]),
        ('Botswana', 'botswana',
         'Kalahari Desert, Okavango Delta, and Africa\u2019s largest elephant population.',
         [('Gaborone District', ['Gaborone']),
          ('Central District', ['Palapye'])]),
        ('Brunei', 'brunei',
         'Oil-rich sultanate on Borneo — golden mosques and pristine rainforest.',
         [('Brunei-Muara', ['Bandar Seri Begawan'])]),
        ('Bulgaria', 'bulgaria',
         'Thracian gold, Byzantine churches, and Black Sea resorts.',
         [('Sofia City Province', ['Sofia']),
          ('Plovdiv Province', ['Plovdiv']),
          ('Varna', ['Varna'])]),
        ('Burkina Faso', 'burkina-faso',
         'Land of upright people — FESPACO film festival and mud-brick architecture.',
         [('Centre', ['Ouagadougou']),
          ('Hauts-Bassins', ['Bobo-Dioulasso'])]),
        ('Burundi', 'burundi',
         'Hill country on Lake Tanganyika — drumming traditions and tea plantations.',
         [('Bujumbura Mairie', ['Bujumbura']),
          ('Bujumbura Rural', ['Gitega'])]),
        # ═══ C ═══
        ('Cabo Verde', 'cabo-verde',
         'Volcanic Atlantic islands — morna music and Portuguese-Creole culture.',
         [('Santiago', ['Praia']),
          ('S\u00e3o Vicente', ['Mindelo'])]),
        ('Cambodia', 'cambodia',
         'Angkor Wat\u2019s temples, French colonial Phnom Penh, and Tonle Sap lake.',
         [('Phnom Penh', ['Phnom Penh']),
          ('Siem Reap', ['Siem Reap']),
          ('Battambang', ['Battambang'])]),
        ('Cameroon', 'cameroon',
         '"Africa in miniature" — beaches, mountains, rainforest, and savanna.',
         [('Centre', ['Yaound\u00e9']),
          ('Littoral', ['Douala']),
          ('Southwest', ['Buea'])]),
        ('Canada', 'canada',
         'From the Rocky Mountains to old-world Qu\u00e9bec — maple, mounties, and multiculturism.',
         [('Ontario', ['Toronto', 'Ottawa']),
          ('Quebec', ['Montreal', 'Quebec City']),
          ('British Columbia', ['Vancouver', 'Victoria']),
          ('Alberta', ['Calgary', 'Edmonton'])]),
        ('Central African Republic', 'central-african-republic',
         'Heart of Africa — dense rainforest, Dzanga bai, and diamond mines.',
         [('Bangui', ['Bangui']),
          ('Haut-Mbomou', ['Bangassou'])]),
        ('Chad', 'chad',
         'Sahel to Sahara — Lake Chad, Tibesti Mountains, and camel caravans.',
         [('N\u2019Djamena Region', ['N\u2019Djamena']),
          ('Logone Occidental', ['Moundou'])]),
        ('Chile', 'chile',
         'A 4,300-km ribbon — Atacama Desert, wine valleys, and Patagonian fjords.',
         [('Santiago Metropolitan', ['Santiago', 'Valpara\u00edso']),
          ('Valpara\u00edso', ['Vi\u00f1a del Mar']),
          ('Biob\u00edo', ['Concepci\u00f3n']),
          ('Antofagasta', ['Antofagasta'])]),
        ('Colombia', 'colombia',
         'Coffee region, Cartagena\u2019s walls, and Bogot\u00e1\u2019s altitude.',
         [('Bogot\u00e1 D.C.', ['Bogot\u00e1']),
          ('Antioquia', ['Medell\u00edn']),
          ('Bol\u00edvar', ['Cartagena']),
          ('Valle del Cauca', ['Cali'])]),
        ('Comoros', 'comoros',
         'Volcanic islands of vanilla, ylang-ylang, and Indian Ocean culture.',
         [('Grande Comore', ['Moroni'])]),
        ('Congo (Brazzaville)', 'congo-brazzaville',
         'Congo River rainforest, Sapeurs fashion, and wild lowland gorillas.',
         [('Brazzaville', ['Brazzaville']),
          ('Pointe-Noire', ['Pointe-Noire'])]),
        ('Costa Rica', 'costa-rica',
         'Pura vida — rainforest canopy tours, volcanoes, and two coastlines.',
         [('San Jos\u00e9', ['San Jos\u00e9']),
          ('Guanacaste', ['Liberia']),
          ('Lim\u00f3n', ['Puerto Lim\u00f3n'])]),
        ('Croatia', 'croatia',
         'Dubrovnik\u2019s walls, Plitvice lakes, and the Adriatic\u2019s sapphire coast.',
         [('Dubrovnik-Neretva', ['Dubrovnik']),
          ('Zagreb', ['Zagreb']),
          ('Split-Dalmatia', ['Split']),
          ('Istria', ['Pula'])]),
        ('Cuba', 'cuba',
         'Habana Vieja, salsa rhythms, and 1950s automobiles frozen in time.',
         [('Havana Province', ['Havana']),
          ('Santiago de Cuba', ['Santiago de Cuba']),
          ('Matanzas', ['Varadero'])]),
        ('Cyprus', 'cyprus',
         'Aphrodite\u2019s island — Byzantine churches and Mediterranean blue.',
         [('Nicosia District', ['Nicosia']),
          ('Limassol District', ['Limassol']),
          ('Paphos District', ['Paphos'])]),
        ('Czechia', 'czechia',
         'Prague Castle spires, beer spas, and Bohemian countryside.',
         [('Prague', ['Prague']),
          ('South Moravian', ['Brno']),
          ('Plze\u0148', ['Plze\u0148'])]),
        # ═══ D ═══
        ('Denmark', 'denmark',
         'Copenhagen\u2019s design, Legoland, and Viking heritage.',
         [('Capital Region', ['Copenhagen']),
          ('Central Jutland', ['Aarhus']),
          ('Southern Denmark', ['Odense'])]),
        ('Djibouti', 'djibouti',
         'Strategic Bab-el-Mandeb — salt lakes, whale sharks, and lunar landscapes.',
         [('Djibouti City Region', ['Djibouti City'])]),
        ('Dominica', 'dominica',
         'The Nature Isle — boiling lake, rainforest, and volcanic hot springs.',
         [('Saint George', ['Roseau'])]),
        ('Dominican Republic', 'dominican-republic',
         'Santo Domingo\u2019s Zona Colonial, Punta Cana beaches, and merengue.',
         [('Distrito Nacional', ['Santo Domingo']),
          ('Santiago', ['Santiago de los Caballeros'])]),
        # ═══ E ═══
        ('Ecuador', 'ecuador',
         'Gal\u00e1pagos Islands, Andean volcanoes, and the equator line.',
         [('Pichincha', ['Quito']),
          ('Guayas', ['Guayaquil']),
          ('Azuay', ['Cuenca'])]),
        ('El Salvador', 'el-salvador',
         'Central America\u2019s smallest nation — volcanoes, pupusas, and Pacific surf.',
         [('San Salvador Department', ['San Salvador']),
          ('Santa Ana', ['Santa Ana'])]),
        ('Equatorial Guinea', 'equatorial-guinea',
         'Oil-rich island-mainland nation on the Gulf of Guinea.',
         [('Bioko Norte', ['Malabo'])]),
        ('Eritrea', 'eritrea',
         'Asmara\u2019s Art Deco and the Red Sea coast of Massawa.',
         [('Central Region', ['Asmara'])]),
        ('Estonia', 'estonia',
         'Digital society, medieval Tallinn, and Baltic coastline.',
         [('Harju County', ['Tallinn']),
          ('Tartu County', ['Tartu'])]),
        ('Eswatini', 'eswatini',
         'Africa\u2019s last absolute monarchy — Reed Dance and wildlife reserves.',
         [('Hhohho', ['Mbabane']),
          ('Manzini', ['Manzini'])]),
        ('Ethiopia', 'ethiopia',
         'Cradle of humanity — Lalibela\u2019s rock churches, Axumite stelae, and coffee origins.',
         [('Addis Ababa', ['Addis Ababa']),
          ('Amhara', ['Gondar', 'Bahir Dar']),
          ('Tigray', ['Mekelle'])]),
        # ═══ F ═══
        ('Fiji', 'fiji',
         '333 islands of coral reefs, kava ceremonies, and South Pacific warmth.',
         [('Central Division', ['Suva']),
          ('Western Division', ['Nadi'])]),
        ('Finland', 'finland',
         'Land of a thousand lakes — Helsinki\u2019s design, Lapland aurora, and saunas.',
         [('Uusimaa', ['Helsinki']),
          ('Pirkanmaa', ['Tampere']),
          ('Southwest Finland', ['Turku'])]),
        # ═══ G ═══
        ('Gabon', 'gabon',
         'Congo Basin rainforest, lowland gorillas, and Loango\u2019s surfing hippos.',
         [('Estuaire', ['Libreville']),
          ('Ogoou\u00e9-Maritime', ['Port-Gentil'])]),
        ('Gambia', 'gambia',
         'A river nation — James Island\u2019s slave-trade history and bird-rich banks.',
         [('Banjul', ['Banjul']),
          ('Kombo', ['Serrekunda'])]),
        ('Georgia', 'georgia-country',
         'Caucasus crossroads — Tbilisi\u2019s sulfur baths, wine country, and Svan towers.',
         [('Tbilisi', ['Tbilisi']),
          ('Adjara', ['Batumi']),
          ('Samegrelo', ['Zugdidi'])]),
        ('Ghana', 'ghana',
         'Cape Coast Castle\u2019s history, Ashanti kingdom, and Accra\u2019s beaches.',
         [('Greater Accra', ['Accra']),
          ('Ashanti', ['Kumasi']),
          ('Central', ['Cape Coast'])]),
        ('Grenada', 'grenada',
         'Isle of Spice — nutmeg plantations and Grand Anse beach.',
         [('Saint George', ['St. George\u2019s'])]),
        ('Guatemala', 'guatemala',
         'Tikal\u2019s Mayan pyramids, Antigua\u2019s colonial ruins, and Lake Atitl\u00e1n.',
         [('Guatemala Department', ['Guatemala City']),
          ('Sacatep\u00e9quez', ['Antigua Guatemala'])]),
        ('Guinea', 'guinea',
         'Fouta Djallon highlands, bauxite wealth, and the source of West African rivers.',
         [('Conakry Region', ['Conakry']),
          ('Nz\u00e9r\u00e9kor\u00e9', ['Nz\u00e9r\u00e9kor\u00e9'])]),
        ('Guinea-Bissau', 'guinea-bissau',
         'Bijag\u00f3s archipelago, cashew groves, and Portuguese Creole culture.',
         [('Bissau Region', ['Bissau'])]),
        ('Guyana', 'guyana',
         'Kaieteur Falls, Amazon rainforest, and English-speaking Caribbean culture in South America.',
         [('Demerara-Mahaica', ['Georgetown'])]),
        # ═══ H ═══
        ('Haiti', 'haiti',
         'First Black republic — Citadelle Laferri\u00e8re, vodou, and vibrant art.',
         [('Ouest', ['Port-au-Prince']),
          ('Nord', ['Cap-Ha\u00eftien'])]),
        ('Honduras', 'honduras',
         'Cop\u00e1n Mayan ruins, Bay Islands diving, and cloud forests.',
         [('Francisco Moraz\u00e1n', ['Tegucigalpa']),
          ('Cort\u00e9s', ['San Pedro Sula'])]),
        ('Hungary', 'hungary',
         'Budapest\u2019s thermal baths, Parliament spires, and the Danube bend.',
         [('Budapest', ['Budapest']),
          ('Pest County', ['Debrecen'])]),
        # ═══ I ═══
        ('Iceland', 'iceland',
         'Geysers, glaciers, geothermal pools, and the Northern Lights.',
         [('Capital Region', ['Reykjav\u00edk']),
          ('Southern Region', ['Vik'])]),
        ('Indonesia', 'indonesia',
         '17,000 islands — Bali\u2019s temples, Jakarta\u2019s energy, and Borobudur\u2019s stupas.',
         [('Jakarta', ['Jakarta']),
          ('Bali', ['Denpasar', 'Ubud']),
          ('Central Java', ['Yogyakarta']),
          ('East Java', ['Surabaya'])]),
        ('Iran', 'iran',
         'Persian gardens, Persepolis ruins, and Isfahan\u2019s blue mosques.',
         [('Tehran Province', ['Tehran']),
          ('Isfahan Province', ['Isfahan']),
          ('Fars Province', ['Shiraz'])]),
        ('Iraq', 'iraq',
         'Cradle of civilization — Babylon\u2019s ruins, Baghdad\u2019s round city, and Mesopotamia.',
         [('Baghdad Governorate', ['Baghdad']),
          ('Erbil Governorate', ['Erbil']),
          ('Basra Governorate', ['Basra'])]),
        ('Ireland', 'ireland',
         'Dublin\u2019s literary pubs, Cliffs of Moher, and forty shades of green.',
         [('Leinster', ['Dublin']),
          ('Munster', ['Cork']),
          ('Connacht', ['Galway'])]),
        ('Israel', 'israel',
         'Jerusalem\u2019s old city, Tel Aviv\u2019s beaches, and Dead Sea salt.',
         [('Tel Aviv District', ['Tel Aviv']),
          ('Jerusalem District', ['Jerusalem']),
          ('Haifa District', ['Haifa'])]),
        ('Ivory Coast', 'ivory-coast',
         'Abidjan\u2019s lagoon skyline, basilica of Yamoussoukro, and cocoa wealth.',
         [('Abidjan District', ['Abidjan']),
          ('Yamoussoukro', ['Yamoussoukro'])]),
        # ═══ J ═══
        ('Jamaica', 'jamaica',
         'Reggae, jerk, Blue Mountain coffee, and Caribbean waterfalls.',
         [('Surrey County', ['Kingston']),
          ('Middlesex County', ['Montego Bay'])]),
        ('Jordan', 'jordan',
         'Petra\u2019s treasury carved in rose-red sandstone and Wadi Rum\u2019s desert.',
         [('Amman Governorate', ['Amman']),
          ('Ma\u2019an Governorate', ['Petra']),
          ('Aqaba', ['Aqaba'])]),
        # ═══ K ═══
        ('Kazakhstan', 'kazakhstan',
         'Steppe to sky — Almaty\u2019s mountains, Astana\u2019s futuristic skyline, and Silk Road cities.',
         [('Almaty Region', ['Almaty']),
          ('Astana City', ['Astana']),
          ('Shymkent', ['Shymkent'])]),
        ('Kenya', 'kenya',
         'Maasai Mara, Mount Kenya, and Nairobi\u2019s tech scene.',
         [('Nairobi County', ['Nairobi']),
          ('Mombasa County', ['Mombasa']),
          ('Kisumu', ['Kisumu'])]),
        ('Kiribati', 'kiribati',
         'Equatorial Pacific atolls — the country that first sees each new dawn.',
         [('South Tarawa', ['Tarawa'])]),
        ('Kosovo', 'kosovo',
         'Europe\u2019s youngest nation — Pristina\u2019s cafes and Decani\u2019s monasteries.',
         [('Pristina District', ['Pristina']),
          ('Pe\u0107 District', ['Pe\u0107'])]),
        ('Kuwait', 'kuwait',
         'Oil wealth, souks, and the Kuwait Towers on the Gulf.',
         [('Al Asimah', ['Kuwait City']),
          ('Hawalli', ['Salmiya'])]),
        ('Kyrgyzstan', 'kyrgyzstan',
         'Tien Shan peaks, yurt camps, and Issyk-Kul\u2019s blue lake.',
         [('Chuy Region', ['Bishkek']),
          ('Issyk-Kul', ['Karakol'])]),
        # ═══ L ═══
        ('Laos', 'laos',
         'Luang Prabang\u2019s temples, Mekong river life, and French colonial charm.',
         [('Vientiane Prefecture', ['Vientiane']),
          ('Luang Prabang Province', ['Luang Prabang']),
          ('Champasak', ['Pakse'])]),
        ('Latvia', 'latvia',
         'Art Nouveau Riga, Baltic pine forests, and Jurmala beaches.',
         [('Riga', ['Riga']),
          ('Zemgale', ['Jelgava'])]),
        ('Lebanon', 'lebanon',
         'Beirut\u2019s energy, cedars of Lebanon, and Roman Baalbek temples.',
         [('Beirut Governorate', ['Beirut']),
          ('Mount Lebanon', ['Byblos', 'Jounieh'])]),
        ('Lesotho', 'lesotho',
         'The kingdom in the sky — all above 1,000 m, draped in Basotho blankets.',
         [('Maseru District', ['Maseru'])]),
        ('Liberia', 'liberia',
         'Founded by freed American slaves — Monrovia\u2019s Providence Island and rubber plantations.',
         [('Montserrado', ['Monrovia'])]),
        ('Libya', 'libya',
         'Leptis Magna Roman ruins, Sahara dunes, and Mediterranean coast.',
         [('Tripoli District', ['Tripoli']),
          ('Benghazi District', ['Benghazi'])]),
        ('Liechtenstein', 'liechtenstein',
         'A microstate of Alpine peaks, Vaduz Castle, and banking.',
         [('Vaduz', ['Vaduz']),
          ('Schaan', ['Schaan'])]),
        ('Lithuania', 'lithuania',
         'Vilnius baroque, Trakai island castle, and amber on the Curonian Spit.',
         [('Vilnius', ['Vilnius']),
          ('Kaunas', ['Kaunas']),
          ('Klaip\u0117da', ['Klaip\u0117da'])]),
        ('Luxembourg', 'luxembourg',
         'A grand duchy of fortified old town, EU institutions, and green valleys.',
         [('Luxembourg Canton', ['Luxembourg City'])]),
        # ═══ M ═══
        ('Madagascar', 'madagascar',
         'A world apart — lemurs, baobab avenues, and biodiversity found nowhere else.',
         [('Analamanga', ['Antananarivo']),
          ('Diana', ['Antsiranana'])]),
        ('Malawi', 'malawi',
         'The warm heart of Africa — Lake Malawi\u2019s freshwater beaches and highlands.',
         [('Lilongwe District', ['Lilongwe']),
          ('Southern Region', ['Blantyre'])]),
        ('Malaysia', 'malaysia',
         'Petronas Towers, rainforest canopy walks, and the multicultural streets of Penang.',
         [('Kuala Lumpur', ['Kuala Lumpur']),
          ('Penang', ['George Town']),
          ('Sabah', ['Kota Kinabalu']),
          ('Sarawak', ['Kuching'])]),
        ('Maldives', 'maldives',
         '1,200 coral islands of overwater bungalows and turquoise lagoons.',
         [('Mal\u00e9 Atoll', ['Mal\u00e9'])]),
        ('Mali', 'mali',
         'Timbuktu\u2019s manuscripts, Bandiagara cliffs, and Niger River life.',
         [('Bamako', ['Bamako']),
          ('Timbuktu Region', ['Timbuktu'])]),
        ('Malta', 'malta',
         'Knights of St. John fortresses, megalithic temples, and Mediterranean blue.',
         [('Central Region', ['Valletta']),
          ('Northern Region', ['Mdina'])]),
        ('Marshall Islands', 'marshall-islands',
         'Pacific atolls of coral reefs, WWII history, and Marshallese stick charts.',
         [('Majuro Atoll', ['Majuro'])]),
        ('Mauritania', 'mauritania',
         'Sahara\u2019s edge — iron-ore trains, ancient Saharan cities, and Atlantic coast.',
         [('Nouakchott', ['Nouakchott'])]),
        ('Mauritius', 'mauritius',
         'Volcanic island of sugar cane, rum, and Creole-French culture.',
         [('Port Louis', ['Port Louis']),
          ('Flacq', ['Curepipe'])]),
        ('Micronesia', 'micronesia',
         'Caroline Islands of Chuuk lagoon wrecks and Nan Madol ruins.',
         [('Yap', ['Colonia'])]),
        ('Moldova', 'moldova',
         'Wine cellars of Cricova, Soviet architecture, and Dniester valleys.',
         [('Chi\u0219in\u0103u', ['Chi\u0219in\u0103u'])]),
        ('Monaco', 'monaco',
         'The glittering principality — Grand Prix, casino, and royal palace.',
         [('Monaco-Ville', ['Monaco-Ville']),
          ('Monte Carlo', ['Monte Carlo'])]),
        ('Mongolia', 'mongolia',
         'Endless steppe, Gobi Desert, and Ulaanbaatar\u2019s modern energy.',
         [('Ulaanbaatar', ['Ulaanbaatar']),
          ('Khangai', ['Kharkhorin'])]),
        ('Montenegro', 'montenegro',
         'Bay of Kotor\u2019s fjord-like beauty, Tara Canyon, and Adriatic old towns.',
         [('Old Royal Capital Cetinje', ['Cetinje']),
          ('Coastal Region', ['Kotor', 'Budva'])]),
        ('Mozambique', 'mozambique',
         '2,500 km of Indian Ocean coast, Mozambique Island\u2019s coral-stone ruins, and marrabenta.',
         [('Maputo City', ['Maputo']),
          ('Nampula', ['Nampula'])]),
        ('Myanmar (Burma)', 'myanmar',
         'Bagan\u2019s temple plains, Shwedagon Pagoda, and Inle Lake stilt villages.',
         [('Yangon Region', ['Yangon']),
          ('Mandalay Region', ['Mandalay']),
          ('Bagan', ['Bagan'])]),
        # ═══ N ═══
        ('Namibia', 'namibia',
         'Sossusvlei\u2019s red dunes, Skeleton Coast fog, and Etosha\u2019s salt pan.',
         [('Khomas', ['Windhoek']),
          ('Erongo', ['Swakopmund'])]),
        ('Nauru', 'nauru',
         'The world\u2019s smallest island nation — phosphate plateau and coral reef ring.',
         [('Yaren', ['Yaren'])]),
        ('Nepal', 'nepal',
         'Himalayan peaks, Kathmandu Valley temples, and Sherpa trails.',
         [('Bagmati', ['Kathmandu', 'Patan', 'Bhaktapur']),
          ('Gandaki', ['Pokhara'])]),
        ('New Zealand', 'new-zealand',
         'Fiordland\u2019s Milford Sound, Maori heritage, and Hobbiton\u2019s green hills.',
         [('Auckland', ['Auckland']),
          ('Wellington', ['Wellington']),
          ('Canterbury', ['Christchurch']),
          ('Otago', ['Queenstown'])]),
        ('Nicaragua', 'nicaragua',
         'Granada\u2019s colonial cathedrals, volcano boarding, and freshwater lakes.',
         [('Managua', ['Managua']),
          ('Granada', ['Granada'])]),
        ('Niger', 'niger',
         'Air Mountains\u2019 rock art, Tuareg caravans, and the Sahel.',
         [('Niamey', ['Niamey'])]),
        ('Nigeria', 'nigeria',
         'Lagos\u2019s Afrobeats energy, Abuja\u2019s planned avenues, and Nollywood film.',
         [('Lagos State', ['Lagos']),
          ('Federal Capital Territory', ['Abuja']),
          ('Kano State', ['Kano'])]),
        ('North Korea', 'north-korea',
         'Pyongyang\u2019s monumental architecture and the DMZ.',
         [('Pyongyang', ['Pyongyang'])]),
        ('North Macedonia', 'north-macedonia',
         'Lake Ohrid\u2019s Byzantine churches, Skopje\u2019s bridges, and mountain monasteries.',
         [('City of Skopje', ['Skopje']),
          ('Ohrid', ['Ohrid'])]),
        ('Norway', 'norway',
         'Fjords, midnight sun, Viking heritage, and Oslo\u2019s modern design.',
         [('Oslo', ['Oslo']),
          ('Vestland', ['Bergen']),
          ('Troms\u00f8', ['Troms\u00f8'])]),
        # ═══ O ═══
        ('Oman', 'oman',
         'Muscat\u2019s whitewashed city, Wahiba Sands, and frankincense trails.',
         [('Muscat Governorate', ['Muscat']),
          ('Dhofar', ['Salalah'])]),
        # ═══ P ═══
        ('Pakistan', 'pakistan',
         'Karakoram peaks, Lahore\u2019s Mughal forts, and Karachi\u2019s Arabian Sea coast.',
         [('Sindh', ['Karachi']),
          ('Punjab', ['Lahore']),
          ('Islamabad Capital Territory', ['Islamabad'])]),
        ('Palau', 'palau',
         'Rock Islands lagoon, Jellyfish Lake, and Pacific diving paradise.',
         [('Koror', ['Koror'])]),
        ('Palestine', 'palestine',
         'Bethlehem\u2019s Church of the Nativity, Hebron\u2019s old city, and olive groves.',
         [('Bethlehem Governorate', ['Bethlehem']),
          ('Gaza Governorate', ['Gaza City'])]),
        ('Panama', 'panama',
         'The canal, Casco Viejo\u2019s colonial quarter, and Bocas del Toro islands.',
         [('Panam\u00e1 Province', ['Panama City']),
          ('Bocas del Toro', ['Bocas Town'])]),
        ('Papua New Guinea', 'papua-new-guinea',
         '800 languages, tribal highlands, and Kokoda Trail jungles.',
         [('National Capital District', ['Port Moresby'])]),
        ('Paraguay', 'paraguay',
         'Guaran\u00ed heritage, Jesuit ruins, and Asunci\u00f3n\u2019s riverfront.',
         [('Asunci\u00f3n', ['Asunci\u00f3n'])]),
        ('Peru', 'peru',
         'Machu Picchu, Nazca Lines, and Lima\u2019s world-class cuisine.',
         [('Lima Province', ['Lima']),
          ('Cusco', ['Cusco', 'Machu Picchu']),
          ('Arequipa', ['Arequipa'])]),
        ('Philippines', 'philippines',
         '7,641 islands — Boracay\u2019s white sand, Palawan\u2019s lagoons, and Manila\u2019s energy.',
         [('Metro Manila', ['Manila']),
          ('Cebu', ['Cebu City']),
          ('Palawan', ['Puerto Princesa'])]),
        ('Poland', 'poland',
         'Krak\u00f3w\u2019s Rynek, Warsaw\u2019s rebuilt old town, and Wieliczka salt mine.',
         [('Masovian', ['Warsaw']),
          ('Lesser Poland', ['Krak\u00f3w']),
          ('Pomeranian', ['Gda\u0144sk'])]),
        ('Portugal', 'portugal',
         'Lisbon\u2019s azulejos, Porto\u2019s port wine, and the Algarve coast.',
         [('Lisbon District', ['Lisbon']),
          ('Porto District', ['Porto']),
          ('Faro District', ['Faro'])]),
        # ═══ R ═══
        ('Romania', 'romania',
         'Transylvania\u2019s castles, painted monasteries, and Bucharest\u2019s grand boulevards.',
         [('Bucharest', ['Bucharest']),
          ('Brasov County', ['Brasov', 'Sibiu']),
          ('Cluj County', ['Cluj-Napoca'])]),
        ('Rwanda', 'rwanda',
         'Land of a thousand hills — mountain gorillas, Lake Kivu, and clean streets.',
         [('Kigali', ['Kigali'])]),
        # ═══ S ═══
        ('Saint Kitts and Nevis', 'saint-kitts-and-nevis',
         'Two-island federation of Brimstone Hill Fortress and Caribbean charm.',
         [('Saint George Basseterre', ['Basseterre'])]),
        ('Saint Lucia', 'saint-lucia',
         'The Pitons\u2019 twin peaks, sulfur springs, and rainforest resorts.',
         [('Castries Quarter', ['Castries'])]),
        ('Saint Vincent and the Grenadines', 'saint-vincent',
         'Volcanic island chain of Pirates of the Caribbean coves and Tobago Cays.',
         [('Saint George', ['Kingstown'])]),
        ('Samoa', 'samoa',
         'Polynesian fa\u2019a Samoa culture, lava fields, and To Sua Ocean Trench.',
         [('Tuamasaga', ['Apia'])]),
        ('San Marino', 'san-marino',
         'The world\u2019s oldest republic — medieval towers on Mount Titano.',
         [('San Marino', ['San Marino'])]),
        ('Sao Tome and Principe', 'sao-tome-and-principe',
         'Equatorial Atlantic islands of cocoa plantations and rainforest peaks.',
         [('Sao Tome', ['Sao Tome'])]),
        ('Saudi Arabia', 'saudi-arabia',
         'Madinah and Makkah\u2019s holy mosques, Riyadh\u2019s skyline, and Empty Quarter dunes.',
         [('Riyadh Province', ['Riyadh']),
          ('Makkah Province', ['Jeddah', 'Mecca']),
          ('Eastern Province', ['Dammam'])]),
        ('Senegal', 'senegal',
         'Dakar\u2019s Gor\u00e9e Island, Saint-Louis\u2019s colonial charm, and mbalax music.',
         [('Dakar', ['Dakar']),
          ('Saint-Louis', ['Saint-Louis'])]),
        ('Serbia', 'serbia',
         'Belgrade\u2019s Kalemegdan fortress, \u0110avolja Varo\u0161 rock formations, and nightlife.',
         [('Belgrade', ['Belgrade']),
          ('Ni\u0161ava', ['Ni\u0161'])]),
        ('Seychelles', 'seychelles',
         '115 granite and coral islands of giant tortoises and Anse Source d\u2019Argent.',
         [('Victoria', ['Victoria'])]),
        ('Sierra Leone', 'sierra-leone',
         'Freetown\u2019s Cotton Tree, Lumley Beach, and diamond-rich Kono hills.',
         [('Western Area', ['Freetown'])]),
        ('Singapore', 'singapore',
         'Gardens by the Bay, Marina Bay Sands, and the world\u2019s best street food.',
         [('Central Region', ['Singapore'])]),
        ('Slovakia', 'slovakia',
         'Bratislava\u2019s castle, Tatra Mountains, and wooden churches.',
         [('Bratislava Region', ['Bratislava']),
          ('Pre\u0161ov', ['Ko\u0161ice'])]),
        ('Slovenia', 'slovenia',
         'Lake Bled\u2019s island church, Ljubljana\u2019s dragon bridge, and Postojna caves.',
         [('Osrednjeslovenska', ['Ljubljana']),
          ('Gorenjska', ['Bled'])]),
        ('Solomon Islands', 'solomon-islands',
         'Pacific archipelago of WWII Guadalcanal and coral atolls.',
         [('Honiara', ['Honiara'])]),
        ('Somalia', 'somalia',
         'Horn of Africa — Mogadishu\u2019s Lido Beach and ancient coastal trade.',
         [('Banaadir', ['Mogadishu'])]),
        ('South Africa', 'south-africa',
         'Cape Town\u2019s Table Mountain, Kruger safaris, and Soweto\u2019s history.',
         [('Western Cape', ['Cape Town']),
          ('Gauteng', ['Johannesburg', 'Pretoria']),
          ('KwaZulu-Natal', ['Durban'])]),
        ('South Korea', 'south-korea',
         'Seoul\u2019s palaces and K-pop, Busan\u2019s beaches, and Jeju\u2019s volcanic island.',
         [('Seoul', ['Seoul']),
          ('Busan', ['Busan']),
          ('Jeju', ['Jeju City'])]),
        ('South Sudan', 'south-sudan',
         'The world\u2019s youngest nation — Nile swamps, cattle camps, and ethnic diversity.',
         [('Juba', ['Juba'])]),
        ('Sri Lanka', 'sri-lanka',
         'Sigiriya\u2019s rock fortress, Ceylon tea estates, and Galle\u2019s Dutch fort.',
         [('Western Province', ['Colombo']),
          ('Central Province', ['Kandy'])]),
        ('Sudan', 'sudan',
         'Mero\u00eb\u2019s pyramids, the confluence of the Blue and White Nile, and Red Sea coast.',
         [('Khartoum State', ['Khartoum'])]),
        ('Suriname', 'suriname',
         'Dutch-speaking Amazon frontier — Paramaribo\u2019s wooden houses and rainforest.',
         [('Paramaribo District', ['Paramaribo'])]),
        ('Sweden', 'sweden',
         'Stockholm\u2019s Gamla Stan, Icehotel, and IKEA design heritage.',
         [('Stockholm County', ['Stockholm']),
          ('V\u00e4stra G\u00f6taland', ['Gothenburg']),
          ('Sk\u00e5ne', ['Malm\u00f6'])]),
        ('Switzerland', 'switzerland',
         'Matterhorn\u2019s peak, Zurich\u2019s banking, and chocolate-box Alpine villages.',
         [('Zurich', ['Zurich']),
          ('Geneva', ['Geneva']),
          ('Bern', ['Bern']),
          ('Valais', ['Zermatt'])]),
        ('Syria', 'syria',
         'Damascus\u2019s Umayyad Mosque, Aleppo\u2019s citadel, and Palmyra\u2019s ruins.',
         [('Damascus Governorate', ['Damascus']),
          ('Aleppo Governorate', ['Aleppo'])]),
        # ═══ T ═══
        ('Taiwan', 'taiwan',
         'Taipei 101, night markets, and Taroko Gorge marble cliffs.',
         [('Taipei City', ['Taipei']),
          ('Kaohsiung', ['Kaohsiung'])]),
        ('Tajikistan', 'tajikistan',
         'Pamir Highway\u2019s high-altitude grandeur, Dushanbe\u2019s squares, and Silk Road forts.',
         [('Dushanbe', ['Dushanbe'])]),
        ('Tanzania', 'tanzania',
         'Serengeti\u2019s migration, Kilimanjaro\u2019s peak, and Zanzibar\u2019s spice islands.',
         [('Dar es Salaam', ['Dar es Salaam']),
          ('Zanzibar', ['Stone Town']),
          ('Arusha', ['Arusha'])]),
        ('Timor-Leste', 'timor-leste',
         'Asia\u2019s youngest nation — Dili\u2019s reefs and Atauro Island diving.',
         [('Dili', ['Dili'])]),
        ('Togo', 'togo',
         'Koutammakou\u2019s mud-tower houses, voodoo traditions, and Atlantic coast.',
         [('Maritime', ['Lom\u00e9'])]),
        ('Tonga', 'tonga',
         'Polynesian kingdom of humpback whales and coral reefs.',
         [('Tongatapu', ['Nuku\u02bbalofa'])]),
        ('Trinidad and Tobago', 'trinidad-and-tobago',
         'Steelpan music, Carnival feathers, and Pitch Lake\u2019s natural asphalt.',
         [('Port of Spain', ['Port of Spain'])]),
        ('Tunisia', 'tunisia',
         'Carthage\u2019s ruins, Sidi Bou Said\u2019s blue doors, and Star Wars desert sets.',
         [('Tunis', ['Tunis']),
          ('Sfax', ['Sfax'])]),
        ('Turkmenistan', 'turkmenistan',
         'Ashgabat\u2019s white-marble grandeur, Darvaza gas crater, and Akhal-Teke horses.',
         [('Ashgabat', ['Ashgabat'])]),
        ('Tuvalu', 'tuvalu',
         'The world\u2019s lowest-lying nation — Funafuti\u2019s atoll and .tv domain.',
         [('Funafuti', ['Funafuti'])]),
        # ═══ U ═══
        ('Uganda', 'uganda',
         'Source of the Nile, mountain gorillas of Bwindi, and Lake Victoria shore.',
         [('Kampala', ['Kampala'])]),
        ('Ukraine', 'ukraine',
         'Kyiv\u2019s golden domes, Lviv\u2019s old town, and the Black Sea coast.',
         [('Kyiv City', ['Kyiv']),
          ('Lviv Oblast', ['Lviv']),
          ('Odessa Oblast', ['Odessa'])]),
        ('Uruguay', 'uruguay',
         'Montevideo\u2019s Rambla, Colonia\u2019s cobblestones, and gaucho pampas.',
         [('Montevideo Department', ['Montevideo']),
          ('Colonia Department', ['Colonia del Sacramento'])]),
        ('Uzbekistan', 'uzbekistan',
         'Samarkand\u2019s Registan, Bukhara\u2019s turquoise domes, and Khiva\u2019s walls.',
         [('Tashkent', ['Tashkent']),
          ('Samarkand', ['Samarkand']),
          ('Bukhara', ['Bukhara'])]),
        # ═══ V ═══
        ('Vanuatu', 'vanuatu',
         'Volcanic islands of Mt. Yasur, banyan trees, and South Pacific diving.',
         [('Shefa', ['Port Vila'])]),
        ('Vatican City', 'vatican-city',
         'St. Peter\u2019s Basilica, the Sistine Chapel, and the world\u2019s smallest state.',
         [('Vatican City', ['Vatican City'])]),
        ('Venezuela', 'venezuela',
         'Angel Falls\u2019 plunge, Los Roques archipelago, and the Andes.',
         [('Capital District', ['Caracas']),
          ('Zulia', ['Maracaibo'])]),
        ('Vietnam', 'vietnam',
         'Ha Long Bay\u2019s karsts, Hanoi\u2019s Old Quarter, and Hoi An lanterns.',
         [('Hanoi', ['Hanoi']),
          ('Ho Chi Minh City', ['Ho Chi Minh City']),
          ('Da Nang', ['Da Nang'])]),
        # ═══ Y ═══
        ('Yemen', 'yemen',
         'Sana\u2019a\u2019s tower houses, Socotra\u2019s dragon-blood trees, and Aden\u2019s harbor.',
         [('Amanat Al Asimah', ['Sana\u2019a']),
          ('Aden', ['Aden'])]),
        # ═══ Z ═══
        ('Zambia', 'zambia',
         'Victoria Falls\u2019 thunder, South Luangwa safaris, and Copperbelt.',
         [('Lusaka Province', ['Lusaka']),
          ('Southern Province', ['Livingstone'])]),
        ('Zimbabwe', 'zimbabwe',
         'Great Zimbabwe ruins, Hwange wildlife, and Matobo balancing rocks.',
         [('Harare', ['Harare']),
          ('Bulawayo', ['Bulawayo'])]),
    ]

    @transaction.atomic
    def handle(self, *args, **options):
        created = {'countries': 0, 'regions': 0, 'cities': 0}

        # Get sort_order offset: start after existing countries
        try:
            max_sort = Country.objects.order_by('-sort_order').first()
            start_sort = (max_sort.sort_order + 1) if max_sort else 0
        except Exception:
            start_sort = 0

        # Collect ALL slugs to ensure uniqueness
        existing_country_slugs = set(Country.objects.values_list('slug', flat=True))
        existing_region_slugs = set(Region.objects.values_list('slug', flat=True))
        existing_city_slugs = set(City.objects.values_list('slug', flat=True))

        for idx, (name, slug, description, regions_data) in enumerate(self.ADDITIONAL_COUNTRIES):
            if slug in existing_country_slugs:
                continue

            country_img = self._img(name, 1200)
            country = Country.objects.create(
                name=name,
                slug=slug,
                image=country_img,
                description=description,
                sort_order=start_sort + idx,
                is_active=True,
            )
            existing_country_slugs.add(slug)
            created['countries'] += 1

            for ridx, (region_name, city_names) in enumerate(regions_data):
                rslug = f'{slug}-{self._slugify(region_name)}'
                # Ensure unique region slug
                base_rslug = rslug
                counter = 1
                while rslug in existing_region_slugs:
                    rslug = f'{base_rslug}-{counter}'
                    counter += 1
                existing_region_slugs.add(rslug)

                region = Region.objects.create(
                    country=country,
                    name=region_name,
                    slug=rslug,
                    image=self._img(f'{name} {region_name}', 900),
                    description=f'Region of {name}.',
                    sort_order=ridx,
                    is_active=True,
                )
                created['regions'] += 1

                for cidx, city_name in enumerate(city_names):
                    cslug = self._slugify(city_name)
                    base_cslug = cslug
                    counter = 1
                    while cslug in existing_city_slugs:
                        cslug = f'{base_cslug}-{counter}'
                        counter += 1
                    existing_city_slugs.add(cslug)

                    City.objects.create(
                        region=region,
                        name=city_name,
                        slug=cslug,
                        image=self._img(f'{name} {city_name}', 900),
                        description=f'{city_name}, {region_name}, {name}.',
                        sort_order=cidx,
                        is_active=True,
                        featured=(cidx == 0),  # first city featured
                    )
                    created['cities'] += 1

        # ── Re-associate products with all cities ──────────
        all_products = list(Product.objects.all())
        all_cities = list(City.objects.all())

        if all_products and all_cities:
            import random
            random.seed(42)
            for product in all_products:
                num_cities = random.randint(1, min(3, len(all_cities)))
                chosen = random.sample(all_cities, num_cities)
                product.cities.set(chosen)

        self.stdout.write(
            self.style.SUCCESS(
                f'Seeded {created["countries"]} countries, '
                f'{created["regions"]} regions, '
                f'{created["cities"]} cities. '
                f'Re-associated {len(all_products)} products with cities.'
            )
        )
