# Generated by Django 5.2.3 on 2026-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_city_country_product_cities_region_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
