# Generated by Django 5.2.3 on 2026-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_city_image_alter_country_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
