# Generated by Django 5.2.3 on 2026-08-05 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_user_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(choices=[('painting', 'AI Painting'), ('mural', 'AI Wall Mural'), ('wallpaper', 'AI Wallpaper Roll'), ('wall-art', 'AI Wall Art'), ('texture', 'AI Texture'), ('kids-nursery', 'AI Kids & Nursery'), ('3d-mural', 'AI 3D Mural'), ('ceiling', 'AI Ceiling Art')], max_length=30)),
                ('prompt', models.TextField()),
                ('enhanced_prompt', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='ai_generated/')),
                ('size', models.CharField(default='1024x1024', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
