# Generated by Django 5.2.3 on 2026-08-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_ai_generated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedimage',
            name='negative_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
